SELECT
   T1.ID
  ,T1.FIRST_NAME
  ,T1.LAST_NAME
  ,T1.SALARY
  ,T1.GRADE
  ,T2.LAST_NAME BOSS_LAST_NAME
  FROM EMPLOYEE T1
  LEFT OUTER JOIN EMPLOYEE T2
    ON T1.BOSS_ID = T2.ID
 WHERE T1.ID = ?
   AND T1.DELETE_FLG = '0'
 ORDER BY ID DESC
